### ISSUE TITLE
Achievement list stuck on ~70 games

### ISSUE THREAD

**Issue by D0geDev** [Ko1ors/Steam-Achievement-Viewer#19]
![image](https://user-images.githubusercontent.com/78917686/205514040-dd9cf39e-da5d-4909-9a78-6abb5c35eb16.png)

**Comment by Ko1ors** [comment]
Partially fixed in [1.01](https://github.com/Ko1ors/Steam-Achievement-Viewer/releases/tag/1.01). A proper and full fix is in work with other improvements and will be available in future releases.

**Comment by Ko1ors** [comment]
Fixed in [1.1](https://github.com/Ko1ors/Steam-Achievement-Viewer/releases/tag/1.1)
